Update installation.md
I needed to run this additional command to install python3.9-specific distutils. Without this, installation of several poetry dependencies (idna, pyparsing, sniffio) failed with message: 
ModuleNotFoundError: No module named 'distutils.cmd'